version: '3.8'

services:
  # AI任务管家服务端
  ai-manager-server:
    build:
      context: ..
      dockerfile: deploy/Dockerfile.server
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - ai-manager-network

  # AI任务管家Web前端
  ai-manager-web:
    build:
      context: ..
      dockerfile: deploy/Dockerfile.web
    ports:
      - "3000:80"
    depends_on:
      - ai-manager-server
    environment:
      - API_URL=http://ai-manager-server:8080
    restart: unless-stopped
    networks:
      - ai-manager-network

  # Nginx反向代理
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - ai-manager-server
      - ai-manager-web
    restart: unless-stopped
    networks:
      - ai-manager-network

networks:
  ai-manager-network:
    driver: bridge

volumes:
  ai-manager-data:
  ai-manager-logs: